/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Andrisa Santos
 */
public class ClienteGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteGUI.class.getName());

    private static final String HOST = "localhost";
    private static final int PORTA = 50000;

    // "uuuu" (ano ISO) em vez de "yyyy" (ano-da-era): com ResolverStyle.STRICT,
    // "yyyy" sozinho não é suficiente para resolver o ano (exigiria também a era),
    // e QUALQUER data seria rejeitada. "uuuu" resolve isso e ainda rejeita
    // corretamente datas absurdas como 31/02/2026 ou 29/02 em ano não bissexto.
    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/uuuu").withResolverStyle(ResolverStyle.STRICT);

    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI() {
        initComponents();

        // Liga o clique de "Enviar" à lógica de rede.
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        // O campo de data começa com o texto "dd/mm/yyyy" já preenchido (não é um
        // placeholder de verdade). Sem isto, quem clica e digita sem apagar acaba
        // misturando o texto digitado com o texto de exemplo, e a validação
        // (corretamente) rejeita o valor. Selecionar tudo ao focar corrige isso:
        // o primeiro clique/tab já deixa o campo pronto para ser sobrescrito.
        txtDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataNascimento.selectAll();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeCompleto = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        lblCadastroAcademico = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        txtNomeCompletoView = new javax.swing.JTextField();
        txtDataNascimentoView = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeCompleto.setText("Nome Completo:");

        lblDataNascimento.setText("Data de Nascimento:");

        txtNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompletoActionPerformed(evt);
            }
        });

        txtDataNascimento.setText("dd/mm/yyyy");

        lblCadastroAcademico.setText("Cadastro Acadêmico");

        btnEnviar.setText("Enviar");

        txtNomeCompletoView.setEditable(false);
        txtNomeCompletoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCompletoViewActionPerformed(evt);
            }
        });

        txtDataNascimentoView.setEditable(false);

        lblCliente.setText("E-mail:");

        txtEmailCliente.setEditable(false);
        txtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClienteActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeCompleto)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDataNascimentoView, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNomeCompletoView, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(lblCadastroAcademico)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviar)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDataNascimento, txtDataNascimentoView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblCadastroAcademico)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(txtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtNomeCompletoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDataNascimentoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnAtualizar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailClienteActionPerformed

    private void txtNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompletoActionPerformed

    private void txtNomeCompletoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCompletoViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCompletoViewActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // Botão de apoio: apenas limpa os campos para um novo cadastro.
        txtNomeCompleto.setText("");
        txtDataNascimento.setText("dd/mm/yyyy");
        txtNomeCompletoView.setText("");
        txtDataNascimentoView.setText("");
        txtEmailCliente.setText("");
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * Chamado pela EDT ao clicar em "Enviar". A validação é feita aqui mesmo
     * (é rápida, não trava nada), mas a comunicação de rede é delegada a uma
     * Thread separada, pois Socket/streams são operações bloqueantes e
     * travariam a interface se rodassem na Event Dispatch Thread.
     */
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        String nome = txtNomeCompleto.getText().trim();
        String dataTexto = txtDataNascimento.getText().trim();

        if (nome.isEmpty() || nome.split("\\s+").length < 2) {
            JOptionPane.showMessageDialog(this, "Informe o nome completo (nome e sobrenome).", "Validação", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            LocalDate.parse(dataTexto, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida. Use o formato dd/MM/yyyy.", "Validação", JOptionPane.WARNING_MESSAGE);
            return;
        }

        btnEnviar.setEnabled(false);
        Pessoa pessoaParaEnviar = new Pessoa(nome, dataTexto, null);

        Thread threadEnvio = new Thread(() -> enviarParaServidor(pessoaParaEnviar));
        threadEnvio.setDaemon(true);
        threadEnvio.start();
    }

    /** Roda fora da EDT. Ao terminar, agenda a atualização da tela via invokeLater. */
    private void enviarParaServidor(Pessoa pessoaParaEnviar) {
        try (Socket socket = new Socket(HOST, PORTA);
             ObjectOutputStream saida = new ObjectOutputStream(socket.getOutputStream());
             ObjectInputStream entrada = new ObjectInputStream(socket.getInputStream())) {

            saida.flush();
            saida.writeObject(pessoaParaEnviar);

            Pessoa pessoaRecebida = (Pessoa) entrada.readObject();

            SwingUtilities.invokeLater(() -> {
                txtNomeCompletoView.setText(pessoaRecebida.getNome());
                txtDataNascimentoView.setText(pessoaRecebida.getDataNascimento());
                txtEmailCliente.setText(pessoaRecebida.getEmail());
                btnEnviar.setEnabled(true);
            });
        } catch (IOException | ClassNotFoundException e) {
            SwingUtilities.invokeLater(() -> {
                JOptionPane.showMessageDialog(this, "Não foi possível falar com o servidor: " + e.getMessage(),
                        "Erro de rede", JOptionPane.ERROR_MESSAGE);
                btnEnviar.setEnabled(true);
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblCadastroAcademico;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtDataNascimentoView;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JTextField txtNomeCompletoView;
    // End of variables declaration//GEN-END:variables
}
